config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { minimum: 4}
  validates :address, :description, presence: true #prevent any new place to be saved without a name

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :delete]
  def index
    @places = Place.all
    # @places = Place.page(params[:page]) -- TRIED TO PAGINATE -- NOT WORKING
    #all places in database stuffed into var @places
  end

  def new
    @place = Place.new #telling the application what I'm building the form for
  end #for the form so people can add in a "new" place

  # def index
  #   @tasks = Task.search(params[:term], params[:page])
  # end

  def create #sends values to database -- same as .create we used on the console 

    @place = current_user.places.create(place_params)

    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def show
    @place = Place.find(params[:id])
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

  end


  def update #how do I know this is the code that will be used when update button is pressed?
    @place = Place.find(params[:id])
    
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end



    @place.update_attributes(place_params)

    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def delete
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end


    @place.destroy

    redirect_to root_path
  end


  private

  def place_params #pulls values
    params.require(:place).permit(:name, :description, :address)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<!-- bootstrap navbar -->
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Nomster</a> -->
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %> 
      <!-- root_path directs back to home page -->

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
            <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
             <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
             <!-- <%= link_to 'No user is signed in :(', '#', class: 'nav-link' %> -->
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
           <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>


<!-- new_user_password GET    /users/password/new(.:format)  devise/passwords#new -->

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1> Edit Your Place </h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>



















<!-- <div class="booyah-box col-10 offset-1">
  <h1> Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>  <!--bootstrap class  
  <% end %>
</div> -->

app/views/places/index.html.erb
<!-- <h1><%= @places.inspect %></h1> -->



<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">  <!-- 10 cols wide and offset by 1 so always in center-->
    <!-- <h1><%= place.name %></h1> -->
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />


    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>
  </div>

<% end %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1> Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>  <!--bootstrap class  -->
  <% end %>
</div>

<!-- I didn't reference this file anywhere, I think it shows up based solely on where it is saved ----- apps/views/places/new ----- THIS IS HWY I CCOULD FIND IT VIA LOCALHOST/PLACES/NEW!!!!!! -->

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1> <%= @place.name %> </h1><br />
  <i><%= @place.address %></i>
  <br /><br />
  <p><%= @place.description %></p>


  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>

      <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you shure you want to delete this?'}, class: 'btn btn-primary' %>
     <% end %>
  </div>
</div>
<!-- once the show action is called, it passes in place[:id] to here and we then display it however we want -->